### ISSUE TITLE
想咨询tensorflow 以及pytorch的版本

### ISSUE THREAD

**Issue by X-CCS** [wqt2019/tacotron-2_wavernn#5]
作者你好！想问问你所用的tensorflow 以及pytorch的版本，谢谢

**Comment by wqt2019** [comment]
1.13和1.4

**Comment by X-CCS** [comment]
谢谢作者！还有个问题是：我用GPU训练的时候总是报`could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`的错误，我用的 `CUDA=10.0 cudnn=7.4.2 `想问问你用的版本是怎么样的？好匹配一下，跑起训练效果，谢谢。

**Comment by wqt2019** [comment]
cuda-10.0  cudnn-7.6.5，主要是跟你的tf和pytorch对应就好了，版本问题应该不大

**Comment by X-CCS** [comment]
好的，谢谢
